# Generated by Django 2.0.4 on 2018-04-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0004_auto_20180423_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_type', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_holder', to='landing.Stylist')),
            ],
        ),
    ]
