# Generated by Django 2.1 on 2018-08-23 02:09

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=25)),
                ('stylist_type', models.CharField(blank=True, choices=[('BARBER', 'Barber'), ('HAIR_STYLIST', 'Hair Stylist'), ('MAKEUP', 'Makeup Artist'), ('MUAH', 'Make Up And Hair'), ('NAILS', 'Nail Technician'), ('CLIENT', 'Client')], max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=25)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(blank=True, max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('about_me', models.TextField(blank=True)),
                ('store_front', models.ImageField(default='/user/storefront/default-storefront.jpg', upload_to=core.models.Account.user_directory_path)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='landing.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(default='/user/gallery/gallery.jpg', upload_to=core.models.Gallery.user_directory_path1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Stylist')),
            ],
        ),
    ]
