# Generated by Django 2.0.4 on 2018-05-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='landing.Stylist'),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='stylist_type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
