# Generated by Django 2.0.4 on 2018-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180510_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='store_front',
            field=models.ImageField(default='/user/storefront/upload.jpg', upload_to='user/storefront/'),
        ),
    ]
