# Generated by Django 2.0.4 on 2018-05-22 05:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_store_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='store_front',
            field=models.ImageField(default='/user/storefront/upload.jpg', upload_to=core.models.Account.user_directory_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='stylist_type',
            field=models.CharField(blank=True, choices=[('BARBER', 'Barber'), ('HAIR_STYLIST', 'Hair Stylist'), ('MAKEUP', 'Makeup Artist'), ('MUAH', 'Make Up And Hair'), ('NAILS', 'Nail Technician')], max_length=25),
        ),
    ]
