# Generated by Django 2.0.4 on 2018-05-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180423_0325'),
        ('core', '0004_auto_20180522_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='/user/storefront/gallery.jpg', upload_to='user_9/gallery')),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='landing.Stylist')),
            ],
        ),
    ]
