# Generated by Django 2.0.4 on 2018-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_account_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('duration', models.DurationField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
    ]
