# Generated by Django 2.0.4 on 2018-06-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180604_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
