# Generated by Django 2.0.4 on 2018-08-22 17:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180604_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='stylist',
        ),
        migrations.AlterField(
            model_name='account',
            name='store_front',
            field=models.ImageField(default='/user/storefront/default-storefront.jpg', upload_to=core.models.Account.user_directory_path),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default='/user/gallery/gallery.jpg', upload_to=core.models.Gallery.user_directory_path1),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
