# Generated by Django 2.0.4 on 2018-08-21 21:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180821_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(default='/user/gallery/gallery.jpg', upload_to=core.models.Gallery.user_directory_path1),
        ),
    ]
