# Generated by Django 2.0.4 on 2018-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
