# Generated by Django 2.1 on 2018-08-23 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
