# Generated by Django 2.0.4 on 2018-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180423_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
