# Generated by Django 2.1 on 2018-08-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_stylista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylista',
            options={'verbose_name': 'Stylista', 'verbose_name_plural': 'Stylistas'},
        ),
        migrations.RenameField(
            model_name='stylista',
            old_name='vendor_id',
            new_name='business_id',
        ),
    ]
