# Generated by Django 2.1 on 2018-08-23 05:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180823_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylista',
            name='services',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
