# Generated by Django 2.1 on 2018-09-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180907_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
