# Generated by Django 2.0.4 on 2018-08-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total_price',
        ),
    ]
